### ISSUE TITLE
Problem when I run /PATE/SHVN/Main.py

### ISSUE THREAD

**Issue by Huangpq2019** [kamathhrishi/PATE#1]
$ python Main.py
Using downloaded and verified file: ../data/train_32x32.mat
Using downloaded and verified file: ../data/test_32x32.mat
TRAINING  model_0
EPOCH:  1
Traceback (most recent call last):
  File "Main.py", line 35, in <module>
    teacher.train(train_loader)
  File "/home/liujj/PATE/SHVN/Teacher.py", line 116, in train
    self.loop_body(split[index],model_name,1)
  File "/home/liujj/PATE/SHVN/Teacher.py", line 129, in loop_body
    output = model(data)
  File "/mnt/data/conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liujj/PATE/SHVN/Model.py", line 18, in forward
    x = F.relu(self.conv1(x))
  File "/mnt/data/conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/data/conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 20 1 5 5, expected input[64, 3, 32, 32] to have 1 channels, but got 3 channels instead

what is the RuntimeError mean? Can you help me solve?

**Comment by kamathhrishi** [comment]
@Huangpq2019 Thank you for raising the issue. I haven't completed the pate example yet :) .  This reason for this issue is simple. I have used the same lenet model for shvn which is incorrect since mnist is 28×28 images and mnist is 32×32 images so dimensions mismatch occurs. I would like to proceed to complete this project end of this month. In next 24-48 hours I will try fixing this issue.

**Comment by jahidhasanlinix** [comment]
May I know when I run this code, do I need any kind of dataset to work with? I actually can't see any datasets available in the repo, that's why asking.
