### ISSUE TITLE
Problem When I run Main.py

### ISSUE THREAD

**Issue by Billy1900** [kamathhrishi/PATE#3]
the error msg is as follows:
<pre>
Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    from Teacher import Teacher
  File "E:\1-Research\0-DP+GCN\Code\(2020-09-20)PATE\Teacher.py", line 6, in <module>
    from syft.frameworks.torch.differential_privacy import pate
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\__init__.py", line 14, in <module>
    import syft.frameworks.torch.hook.hook_args
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\hook\hook_args.py", line 4, in <module>
    from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\tensors\interpreters\native.py", line 11, in <module>
    from syft.messaging.message import TensorCommandMessage
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\messaging\message.py", line 17, in <module>
    from syft.execution.action import Action
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\action.py", line 5, in <module>
    from syft.execution.placeholder import PlaceHolder
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\placeholder.py", line 7, in <module>
    from syft_proto.execution.v1.placeholder_pb2 import Placeholder as PlaceholderPB
  File "D:\Anaconda\envs\torch\lib\site-packages\syft_proto-0.5.2-py3.7.egg\syft_proto\execution\v1\placeholder_pb2.py", line 14, in <module>
    from syft_proto.types.syft.v1 import id_pb2 as syft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2
  File "D:\Anaconda\envs\torch\lib\site-packages\syft_proto-0.5.2-py3.7.egg\syft_proto\types\syft\v1\id_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
</pre>

**Comment by Billy1900** [comment]
ok, when I upgrade protobuf from this [Link](https://stackoverflow.com/questions/61922334/how-to-solve-attributeerror-module-google-protobuf-descriptor-has-no-attribu), another problem occured, 
<pre>
Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    from Teacher import Teacher
  File "E:\1-Research\0-DP+GCN\Code\(2020-09-20)PATE\Teacher.py", line 6, in <module>
    from syft.frameworks.torch.differential_privacy import pate
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\__init__.py", line 14, in <module>
    import syft.frameworks.torch.hook.hook_args
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\hook\hook_args.py", line 4, in <module>
    from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\tensors\interpreters\native.py", line 16, in <module>
    from syft.generic.utils import memorize
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\utils.py", line 1, in <module>
    from syft.generic.frameworks.attributes import allowed_commands
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\attributes.py", line 8, in <module>
    from syft.generic.frameworks.hook.hook import FrameworkHook
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\hook\hook.py", line 11, in <module>
    from syft.generic.frameworks.hook.pointers import PointerHook
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\hook\pointers.py", line 8, in <module>
    from syft.generic.pointers.multi_pointer import MultiPointerTensor
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\pointers\multi_pointer.py", line 11, in <module>
    from syft.workers.base import BaseWorker
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\workers\base.py", line 12, in <module>
    from syft.execution.plan import Plan
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\plan.py", line 21, in <module>
    from syft.execution.translation.threepio import PlanTranslatorTfjs
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\translation\threepio.py", line 2, in <module>
    import pythreepio
ModuleNotFoundError: No module named 'pythreepio'
</pre>

**Comment by Billy1900** [comment]
I solved it by myself. 

1) First, uninstall the original pysyft--`pip uninstall syft`. 

2) And then to use this command `pip install syft -f https://download.pytorch.org/whl/torch_stable.html` from this [link](https://stackoverflow.com/questions/61850455/could-not-find-a-version-that-satisfies-the-requirement-torch-1-4-0-from-syft)

3) maybe you will meet this problem, `ModuleNotFoundError: No module named 'syft.frameworks.torch.differential_privacy'`, please change it into `ModuleNotFoundError: No module named 'syft.frameworks.torch.dp` according to this [link](https://stackoverflow.com/questions/58367187/modulenotfounderror-no-module-named-syft-pysyft)
